name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream
        uses: tgymrek/sync-fork-action@v1.5
        with:
          upstream_repo: raikikon/mobin # Replace with original
          upstream_branch: main
          target_repo: feelslikeflying/mobin # Replace with yours
          target_branch: main
          github_token: ${{ env.REPO_BASENAME }}  # Need a Personal Access Token
